interface fs {
    /// A file.
    resource file {
        open: static func(path: string) -> result<file, errno>;
        read: func(len: u32) -> result<list<u8>, errno>;
        write: func(data: list<u8>) -> result<_, errno>;
        close: func() -> result<_, errno>;
    }

    /// Common errors that may occur during filesystem operations.
    enum errno {
        not-found,
        already-closed,
        unknown,
    }
}
